const movies = [
  {
    id: "1",
    title: "fdkdk",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "images/R.jpeg",
    description: "A skilled thief is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.",
    year: 2010,
    interpreter: "ROCKY",
    genre: ["Action", "Sci-Fi", "Thriller"],
    watchLink: "https://youtu.be/QkJH2lK7usw?si=vFk_I5vU_B26Gqbj",
    downloadLink: "https://youtu.be/54dnv1ha3sw?si=EcbdYVxYqkhwOTSs"
  },
  {
    id: "2",
    title: "The Dark Knight",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "images/darkknight.jpg",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    year: 2008,
    interpreter: "Christopher Nolan",
    genre: ["Action", "Crime", "Drama"],
    watchLink: "https://example.com/watch/darkknight",
    downloadLink: "https://example.com/download/darkknight"
  },
  {
    id: "3",
    title: "Breaking Bad",
    type: "series",
    isFeatured: false,
    isPopular: true,
    poster: "images/breakingbad.jpg",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future.",
    year: 2008,
    interpreter: "Vince Gilligan",
    genre: ["Crime", "Drama", "Thriller"],
    watchLink: "https://example.com/watch/breakingbad",
    downloadLink: "https://example.com/download/breakingbad"
  },
  {
    id: "4",
    title: "Stranger Things",
    type: "series",
    isFeatured: true,
    isPopular: true,
    poster: "images/strangerthings.jpg",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    year: 2016,
    interpreter: "Duffer Brothers",
    genre: ["Drama", "Fantasy", "Horror"],
    watchLink: "https://example.com/watch/strangerthings",
    downloadLink: "https://example.com/download/strangerthings"
  },
  {
    id: "5",
    title: "The Matrix",
    type: "movie",
    isFeatured: false,
    isPopular: true,
    poster: "images/matrix.jpg",
    description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to free humanity.",
    year: 1999,
    interpreter: "Wachowski Brothers",
    genre: ["Action", "Sci-Fi"],
    watchLink: "https://example.com/watch/matrix",
    downloadLink: "https://example.com/download/matrix"
  },
  {
    id: "6",
    title: "The Crown",
    type: "series",
    isFeatured: false,
    isPopular: false,
    poster: "images/crown.jpg",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    year: 2016,
    interpreter: "Peter Morgan",
    genre: ["Drama", "History"],
    watchLink: "https://example.com/watch/crown",
    downloadLink: "https://example.com/download/crown"
  },
  {
    id: "7",
    title: "Interstellar",
    type: "movie",
    isFeatured: true,
    isPopular: false,
    poster: "images/interstellar.jpg",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    year: 2014,
    interpreter: "Christopher Nolan",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    watchLink: "https://example.com/watch/interstellar",
    downloadLink: "https://example.com/download/interstellar"
  },
  {
    id: "8",
    title: "The Office",
    type: "series",
    isFeatured: false,
    isPopular: true,
    poster: "images/office.jpg",
    description: "A mockumentary sitcom that depicts the everyday work lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
    year: 2005,
    interpreter: "Ricky Gervais",
    genre: ["Comedy"],
    watchLink: "https://example.com/watch/office",
    downloadLink: "https://example.com/download/office"
  },
  {
    id: "9",
    title: "Pulp Fiction",
    type: "movie",
    isFeatured: false,
    isPopular: false,
    poster: "images/pulpfiction.jpg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 1994,
    interpreter: "Quentin Tarantino",
    genre: ["Crime", "Drama"],
    watchLink: "https://example.com/watch/pulpfiction",
    downloadLink: "https://example.com/download/pulpfiction"
  },
  {
    id: "10",
    title: "Friends",
    type: "series",
    isFeatured: false,
    isPopular: true,
    poster: "images/friends.jpg",
    description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    year: 1994,
    interpreter: "Marta Kauffman",
    genre: ["Comedy", "Romance"],
    watchLink: "https://example.com/watch/friends",
    downloadLink: "https://example.com/download/friends"
  }
];
