const movies = [
{
    id: "1",
    title: "FATALE A",
    type: "ACTIONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/f.jpg",
    description: "A skilled thief is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.",
    year: 2010,
    interpreter: "ROCKY",
    genre: ["Action"],
    watchLink: "https://agasobanuye.seekplayer.me/#hb3xf",
    downloadLink: "https://agasobanuye.seekplayer.me/#hb3xf&dl=1"
  },
  {
    id: "5",
    title: "FATALE B",
    type: "ACTIONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/f.jpg",
    description: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to free humanity.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["Action", ],
    watchLink: "https://agasobanuye.seekplayer.me/#cpce1",
    downloadLink: "https://agasobanuye.seekplayer.me/#cpce1&dl=1"
  },
  {
    id: "2",
    title: "WU ASSASSINS S1E1",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/wu.jpg",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    year: 2008,
    interpreter: "ROCKY",
    genre: ["Action"],
    watchLink: "https://www.mediafire.com/file/rihwokl1ds836r0/S01_-_EP01_-_Wu_Assassins.mp4.mp4/file",
    downloadLink: "https://www.mediafire.com/file/rihwokl1ds836r0/S01_-_EP01_-_Wu_Assassins.mp4.mp4/file"
  },
   {
    id: "7",
    title: "WU ASSASSINS S1E2",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/wu.jpg",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    year: 2016,
    
    interpreter: "ROCKY",
    genre: ["series"],
    watchLink: "https://agasobanuye.seekplayer.me/#bn6ct",
    downloadLink: "https://agasobanuye.seekplayer.me/#bn6ct&dl=1"
  
  },
  {
    id: "4",
    title: "WU ASSASSINS S1E3",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/wu.jpg",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    year: 2016,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#sjcks",
    downloadLink: "https://agasobanuye.seekplayer.me/#sjcks&dl=1"
  },
  
  
  
  {
    id: "6",
    title: "BEAUTY IN BLACK S3E1",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/B.webp",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    year: 2016,
    interpreter: "ROCKY",
    genre: ["Drama", "History"],
    watchLink: "https://agasobanuye.seekplayer.me/#kt8vz",
    downloadLink: "https://agasobanuye.seekplayer.me/#kt8vz&dl=1"
  },
  {
    id: "7",
    title: "BEAUTY IN BLACK S3E2",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/B.webp",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    year: 2014,
    interpreter: "ROCKY",
    genre: ["MOVIES"],
    watchLink: "https://agasobanuye.seekplayer.me/#i95ff",
    downloadLink: "https://agasobanuye.seekplayer.me/#i95ff&dl=1"
     },
     {
    id: "10",
    title: "BEAUTY IN BLACK S3E3",
    type: "SEASONS",
    isFeatured: true,
    isPopular: true,
    poster: "/images/B.webp",
    description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["MOVIES"],
    watchLink: "https://agasobanuye.seekplayer.me/#5u5mx",
    downloadLink: "https://agasobanuye.seekplayer.me/#5u5mx&dl=1"
  },
  {
    
  
    id: "3",
    title: "BEAUTY IN BLACK S3E4",
    type: "series",
    isFeatured: true,
    isPopular: true,
    poster: "/images/B.webp",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["series"],
    watchLink: "https://agasobanuye.seekplayer.me/#mqeaf",
    downloadLink: "https://agasobanuye.seekplayer.me/#mqeaf&dl=1"
  },
 
  {
    id: "11",
    title: "PAD MAN A",
    isFeatured: true,
    isPopular: true,
    poster: "/images/PadMan-poster-2.jpg",
    description: "A mockumentary sitcom that depicts the everyday work lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  
   {
    id: "13",
    title: "PAD MAN B",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "images/PadMan-poster-2.jpg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  {
    id: "12",
    title: "BLOOD RED SKY",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
   {
    id: "14",
    title: "FLIGHT 666",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "SANKARA",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#jydg5",
    downloadLink: "https://agasobanuye.seekplayer.me/#jydg5&dl=1"
  }, {
    id: "15",
    title: "COUNT DAWN",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/COUNT.webp",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#lujii",
    downloadLink: "https://agasobanuye.seekplayer.me/#lujii&dl=1"
  },
  {
    id: "16",
    title: "",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  {
    id: "17",
    title: "BLOOD RED SKY",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  {
    id: "18",
    title: "BLOOD RED SKY",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  {
    id: "19",
    title: "BLOOD RED SKY",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/RED.jpeg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#v8ind",
    downloadLink: "https://agasobanuye.seekplayer.me/#v8ind&dl=1"
  },
  {
    id: "20",
    title: "HOBBS AND SHOW",
    type: "movie",
    isFeatured: true,
    isPopular: true,
    poster: "/images/H.jpg",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    year: 2026,
    interpreter: "ROCKY",
    genre: ["ACTION"],
    watchLink: "https://agasobanuye.seekplayer.me/#bvqji",
    downloadLink: "https://agasobanuye.seekplayer.me/#bvqji&dl=1"
  },
];
